name: Build and Test

on: [push, pull_request]

jobs:
  unit-test:
    name: Run Jest tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test --forceExit --runInBand

  integration-and-e2e-test:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_URL: http://localhost:3000/api
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.0'

      - name: Cache Next.js build
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}

      - name: Cypress run
        uses: cypress-io/github-action@v2.7.0
        continue-on-error: true
        with:
          record: true
          group: merge
          browser: chrome
          tag: ${{ github.event_name }}
          config: baseUrl=http://localhost:3000
          env: api_url=http://localhost:3000/api
          install-command: yarn --frozen-lockfile
          build: yarn build
          start: yarn test:e2e
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
