name: Deploy Serverless Production

on:
  push:
    branches:
      - production

jobs:
  deploy-production:
    name: Deploys serverless function to 'production' stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile     

      - name: Deploy Lambda functions
        run: npx serverless deploy --stage production --profile '' --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
