name: Deploy Serverless Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    name: Deploys serverless function to 'staging' stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.20.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Deploy Lambda functions
        run: npx serverless deploy --stage staging --profile '' --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.STAGING_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.STAGING_AWS_SECRET_KEY }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
